USE community;
INSERT INTO name (first_name, middle_name, last_name) VALUES ("James", "Albert", "Peterson");
INSERT INTO name (first_name, last_name) VALUES ("Mike", "Rodgers");
INSERT INTO name (first_name, middle_name, last_name) VALUES ("Justin", "Issac", "Clark");
INSERT INTO name (first_name, middle_name, last_name) VALUES ("Barry", "Henry", "Farese");
INSERT INTO name (first_name, middle_name, last_name) VALUES ("Aaron", "Benjamin", "Lorio");
INSERT INTO name (first_name, middle_name, last_name) VALUES ("Justin", "Wayne", "Smith");
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("123 Jefferson St", "TX", "45678", 1);
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("321 Easy St", "MD", "45748", 2);
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("465 Adventure Way", "NH", "32457", 3);
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("4783 American Blvd", "NY", "97354", 4);
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("775 California Ave", "NV", "03647", 5);
INSERT INTO address (roadway, state, zip_code, namekey) VALUES ("936 Desert Rd", "NM", "21487", 6);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7890", 1);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7874", 2);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7932", 3);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7046", 4);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7821", 5);
INSERT INTO phonenumber (phone_number, namekey) VALUES ("+1-123-456-7562", 6);
desc name;
desc address;
desc phonenumber;
SELECT * FROM name;
SELECT * FROM address;
SELECT * FROM phonenumber;
